algo = input('Digite algo: ')

print(f'algo é um número? {algo.isalnum()}' )
print(f'algo é um caractere alfabetico? {algo.isalpha()}')
print(f'algo é um caractere ascii? {algo.isascii()}')
print(f'algo é um decimal? {algo.isdecimal()}')
print(f'algo é um digito? {algo.isdigit()}')
print(f'algo é um identificador? {algo.isidentifier()}')
print(f'algo é minusculo? {algo.islower()}')
print(f'algo é numérico? {algo.isnumeric()}')
print(f'algo é printavel? {algo.isprintable()}')
print(f'algo é espaço? {algo.isspace()}')
print(f'algo é um título? {algo.istitle()}')
print(f'algo é maiúsculo? {algo.isupper()}')